
version: 2

sources:
  - name: chrome_history
    database: dbt_db
    schema: chrome_schema
    tables:
      - name: raw_history
        columns:
          - name: id
            tests:
              - unique
              - not_null
